// cities.js
export const canadianCities = [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Oakville",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "Halifax",
    "London",
    "Victoria",
    "Saskatoon",
    "Regina",
    "St. John's",
    "Windsor",
    "Barrie",
    "Kelowna",
    "Sherbrooke",
    "Guelph",
    "Kingston",
    "Moncton",
    "Sudbury",
    "Abbotsford",
    "Thunder Bay",
    "Saint John",
    "Chicoutimi",
    "Trois-Rivières",
    "Peterborough",
    "Lethbridge",
    "Saint-Jérôme",
    "Kamloops",
    "Saguenay",
    "Chilliwack",
    "Belleville",
    "Sarnia",
    "Drummondville",
    "Prince George",
    "Red Deer",
    "Laval",
    "Brampton",
    "Mississauga",
    "Markham",
    "Burlington",
    "Oshawa",
    "Gatineau",
    "Longueuil",
    "Surrey",
    "Coquitlam",
    "Richmond",
    "Langley",
    "New Westminster",
    "Burnaby",
    "Maple Ridge",
    "Sault Ste. Marie",
    "North Bay",
    "Timmins",
    "Cornwall",
    "Medicine Hat",
    "Fort McMurray",
    "Grande Prairie",
    "Whitehorse",
    "Yellowknife",
    "Iqaluit"
  ];
  